spring:
  datasource:
    url: jdbc:h2:mem:testdb
    driver-class-name: org.h2.Driver
    username: sa
    password:
  jpa:
    database-platform: org.hibernate.dialect.H2Dialect
    hibernate:
      ddl-auto: update
      show-sql: true
  h2:
    console:
      enabled: true

loans:
  msg: Welcome to the EazyBank Loan Default application
  build-version: 2
  mailDetails:
    hostName: default-loans@eazybytes.com
  activeBranches:
    - "Chennai"
    - "Berlin"
    - "Toronto"

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:6060/eureka/

info:
  app:
    name: Loan Microservice
    description: Easy Bank Loan Application
    version: 1.0.0

management:
  endpoint:
    shutdown:
      enabled: true
  info:
    env:
      enabled: true
  endpoints:
    web:
      exposure:
        include: "*"

endpoints:
  shutdown:
    enabled: true